volumes:
  postgres-data:
    external: true
  pg-admin:
    external: true

services:
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=rentovation@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_DISABLE_POSTFIX=1

  postgres:
    image: postgres:14.5-bullseye
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=example_user
      - POSTGRES_DB=example_db
    ports:
      - 15432:5432

  fastapi:
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    environment:
      - DATABASE_URL=postgresql://example_user:secret@postgres/example_db
      - CORS_HOST=http://localhost:3000
      - WAIT_HOSTS=postgres:5432
      - PORT=8000
      - SIGNING_KEY=f1cc7557872c23818e2740dce07e1ed780a9238ff9e96e778914928d4aa4a66b
      - DB_NAME=db-name-for-your-app-db
      - DB_URL=mongodb://example_user:secret@mongo

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      - HOST_OS=${OS}
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PUBLIC_URL=http://localhost:3000
      - REACT_APP_API_HOST=${REACT_APP_API_HOST}
